import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const VIDEO_WIDTH = width / 2;
const TOP_BAR_HEIGHT = 60;
const BOTTOM_NAV_HEIGHT = 85;
const AVAILABLE_HEIGHT = height - TOP_BAR_HEIGHT;
const VIDEO_HEIGHT = AVAILABLE_HEIGHT * 1.2;
const MIN_CHAT_HEIGHT = AVAILABLE_HEIGHT * 0.15;
const MAX_CHAT_HEIGHT = AVAILABLE_HEIGHT * 0.7;
const DEFAULT_OPEN_HEIGHT = AVAILABLE_HEIGHT * 0.3;

export const styles = StyleSheet.create({
    container: {
        width,
        height,
        flexDirection: 'row',
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#0a0a1a',
    },
    videoWrapper: {
        width: VIDEO_WIDTH,
        height: VIDEO_HEIGHT,
        position: 'relative',
        alignSelf: 'center',
    },
    videoContainer: {
        width: '100%',
        height: '100%',
        position: 'relative',
        paddingHorizontal: 2,
        paddingVertical: 2,
    },
    frameBorder: {
        width: '100%',
        height: '100%',
        borderRadius: 8,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.6,
        shadowRadius: 12,
        elevation: 12,
        borderRightWidth: 3,
        borderTopWidth: 2,
        borderBottomWidth: 2,
    },
    frameInner: {
        width: '100%',
        height: '100%',
        backgroundColor: '#000',
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    video: {
        width: '100%',
        height: '100%',
    },
    videoOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '40%',
    },
    labelContainer: {
        position: 'absolute',
        bottom: 24,
        left: 0,
        right: 0,
        alignItems: 'center',
        zIndex: 8,
    },
    labelBadge: {
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderWidth: 1.5,
    },
    labelText: {
        color: '#ffffff',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 2,
        textTransform: 'uppercase',
    },
    vsContainer: {
        position: 'absolute',
        left: width / 2 - 100,
        top: '50%',
        marginTop: -100,
        width: 200,
        height: 200,
        zIndex: 20,
        alignItems: 'center',
        justifyContent: 'center',
        pointerEvents: 'none',
    },
    vsImage: {
        width: '100%',
        height: '100%',
    },
    scoreContainer: {
        position: 'absolute',
        top: TOP_BAR_HEIGHT + 20,
        left: 0,
        right: 0,
        paddingHorizontal: 16,
        zIndex: 25,
    },
    scoreRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    scoreText: {
        fontSize: 14,
        fontWeight: '800',
        flex: 1,
    },
    timerText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '800',
        paddingHorizontal: 12,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    progressBar: {
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 3,
        overflow: 'hidden',
        flexDirection: 'row',
    },
    progressFill: {
        height: '100%',
    },
    dividerLineLeft: {
        position: 'absolute',
        left: width / 2 - 1.5,
        top: 0,
        bottom: 0,
        width: 3,
        backgroundColor: '#ff2d6f',
        zIndex: 15,
        opacity: 0.8,
    },
    dividerLineRight: {
        position: 'absolute',
        left: width / 2 + 1.5,
        top: 0,
        bottom: 0,
        width: 3,
        backgroundColor: '#37a0ff',
        zIndex: 15,
        opacity: 0.8,
    },
    chatOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 19,
        backgroundColor: 'transparent',
    },
    chatContainerWrapper: {
        position: 'absolute',
        bottom: BOTTOM_NAV_HEIGHT + 10,
        left: 0,
        right: 0,
        width: '100%',
        paddingHorizontal: 8,
        paddingBottom: 8,
        zIndex: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
        elevation: 15,
    },
    chatSection: {
        width: '100%',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
        overflow: 'hidden',
        minHeight: 80,
    },
    chatGradientBackground: {
        flex: 1,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
        borderWidth: 2,
        borderColor: 'rgba(255, 45, 111, 0.4)',
        overflow: 'hidden',
        flexDirection: 'column',
    },
    chatDragHandle: {
        width: '100%',
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 10,
        paddingBottom: 4,
        zIndex: 10,
    },
    chatDragIndicator: {
        width: 48,
        height: 5,
        borderRadius: 3,
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
    },
    chatCollapsed: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        paddingHorizontal: 16,
        gap: 8,
        minHeight: 80,
    },
    chatCollapsedText: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
    },
    chatContentWrapper: {
        flex: 1,
        flexDirection: 'column',
        minHeight: 0,
    },
    chatHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 45, 111, 0.3)',
        minHeight: 48,
        flexShrink: 0,
    },
    chatHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
    },
    chatHeaderRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flexShrink: 0,
    },
    chatCloseButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    chatHeaderText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '800',
        letterSpacing: 0.3,
        flexShrink: 1,
    },
    chatCountBadge: {
        backgroundColor: 'rgba(255, 45, 111, 0.3)',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 12,
        borderWidth: 1,
        minWidth: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    chatCount: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '800',
    },
    chatMessages: {
        flex: 1,
        paddingHorizontal: 16,
        paddingVertical: 8,
        maxHeight: '100%',
    },
    chatContent: {
        paddingBottom: 8,
        flexGrow: 1,
    },
    chatMessage: {
        flexDirection: 'row',
        marginBottom: 8,
        paddingVertical: 4,
        alignItems: 'flex-start',
    },
    chatMessageLast: {
        marginBottom: 4,
    },
    chatUser: {
        fontSize: 13,
        fontWeight: '800',
        marginRight: 6,
        flexShrink: 0,
    },
    chatText: {
        color: 'rgba(255, 255, 255, 0.9)',
        fontSize: 13,
        flex: 1,
        lineHeight: 18,
        flexWrap: 'wrap',
    },
    chatInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 12,
        gap: 8,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 45, 111, 0.2)',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        minHeight: 64,
        maxHeight: 64,
        zIndex: 100,
    },
    chatInput: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 10,
        color: '#fff',
        fontSize: 14,
        borderWidth: 1.5,
        minHeight: 40,
        maxHeight: 40,
    },
    sendButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#ff2d6f',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.6,
        shadowRadius: 6,
        elevation: 6,
        flexShrink: 0,
    },
    sendButtonGradient: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    giftButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#ff2d6f',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.6,
        shadowRadius: 6,
        elevation: 6,
        flexShrink: 0,
    },
    giftButtonGradient: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    giftButtonEmoji: {
        fontSize: 20,
    },
    giftAnimation: {
        position: 'absolute',
        width: 60,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
    },
    giftEmoji: {
        fontSize: 50,
    },
    giftsModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'flex-end',
        zIndex: 9999,
        elevation: 9999,
    },
    giftsModalContent: {
        backgroundColor: 'rgba(10, 10, 26, 0.95)',
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        maxHeight: height * 0.6,
        paddingBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
        elevation: 21,
        zIndex: 10000,
    },
    giftsModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 45, 111, 0.3)',
    },
    giftsModalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '800',
    },
    giftsModalClose: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    giftsList: {
        flex: 1,
    },
    giftsListContent: {
        padding: 16,
        gap: 12,
    },
    giftItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 16,
        padding: 16,
        gap: 16,
    },
    giftItemEmojiContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    giftItemEmoji: {
        fontSize: 36,
    },
    giftItemInfo: {
        flex: 1,
    },
    giftItemName: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 4,
    },
    giftItemPrice: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
    },
    sideSelectionContainer: {
        padding: 20,
        alignItems: 'center',
    },
    sideSelectionTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 24,
        textAlign: 'center',
    },
    sideSelectionButtons: {
        flexDirection: 'row',
        gap: 16,
        width: '100%',
        marginBottom: 20,
    },
    sideSelectionButton: {
        flex: 1,
        borderRadius: 20,
        borderWidth: 2,
        overflow: 'hidden',
        minHeight: 180,
    },
    sideSelectionGradient: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        gap: 12,
    },
    sideSelectionEmoji: {
        fontSize: 48,
        marginBottom: 8,
    },
    sideSelectionName: {
        fontSize: 18,
        fontWeight: '800',
        marginBottom: 4,
    },
    sideSelectionHandle: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 14,
    },
    backButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    backButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
});


