import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    gradientContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
        paddingTop: 35,
        paddingBottom: 12,
    },
    container: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 16,
        gap: 8,
    },
    tab: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 8,
        position: 'relative',
        minWidth: 80,
    },
    tabText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 15,
        fontWeight: '600',
        textShadowColor: 'rgba(0, 0, 0, 0.8)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    tabTextActive: {
        color: '#FFFFFF',
        fontWeight: '800',
        fontSize: 16,
        textShadowColor: 'rgba(0, 0, 0, 1)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 4,
    },
    tabUnderline: {
        position: 'absolute',
        bottom: 4,
        left: '25%',
        right: '25%',
        height: 3,
        backgroundColor: '#FFFFFF',
        borderRadius: 2,
        shadowColor: '#FFFFFF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 4,
    },
    searchButton: {
        padding: 8,
        marginLeft: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        borderRadius: 20,
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
    },
    subMenuContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 4,
        paddingBottom: 8,
        gap: 12,
    },
    subMenuTab: {
        paddingHorizontal: 16,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
    },
    subMenuTabActive: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    subMenuText: {
        color: 'rgba(255, 255, 255, 0.5)',
        fontSize: 11,
        fontWeight: '500',
    },
    subMenuTextActive: {
        color: '#FFFFFF',
        fontWeight: '700',
    },
});

